# Generated by Django 5.0 on 2023-12-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_battles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Battles',
            new_name='Battle',
        ),
    ]
