# Generated by Django 5.0 on 2023-12-22 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_battles_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('A', 'Normal'), ('B', 'Fire'), ('C', 'Water'), ('D', 'Electric'), ('E', 'Grass'), ('F', 'Ice'), ('G', 'Fighting'), ('H', 'Poison'), ('I', 'Ground'), ('J', 'Flying'), ('K', 'Psychic'), ('L', 'Bug'), ('M', 'Rock'), ('N', 'Ghost'), ('O', 'Dragon'), ('P', 'Dark'), ('Q', 'Steel'), ('R', 'Fairy')], default='A', max_length=1)),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('pp', models.IntegerField()),
                ('category', models.CharField(choices=[('P', 'Physical'), ('S', 'Special'), ('T', 'Status')], default='P', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='battle',
            name='date',
            field=models.DateField(verbose_name='Battle Date'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='result',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], default='W', max_length=1),
        ),
    ]
